
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class PackageBuilderMainPage
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label packageNameLabel;
		private global::Gtk.Entry packageNameEntry;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.PackageBuilderMainPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TraceLab.UI.GTK.PackageBuilderMainPage";
			// Container child TraceLab.UI.GTK.PackageBuilderMainPage.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(4));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.packageNameLabel = new global::Gtk.Label ();
			this.packageNameLabel.Name = "packageNameLabel";
			this.packageNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Package Name:");
			this.hbox1.Add (this.packageNameLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.packageNameLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.packageNameEntry = new global::Gtk.Entry ();
			this.packageNameEntry.CanFocus = true;
			this.packageNameEntry.Name = "packageNameEntry";
			this.packageNameEntry.IsEditable = true;
			this.packageNameEntry.InvisibleChar = '●';
			this.hbox1.Add (this.packageNameEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.packageNameEntry]));
			w2.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeView = new global::Gtk.TreeView ();
			this.treeView.CanFocus = true;
			this.treeView.Name = "treeView";
			this.GtkScrolledWindow.Add (this.treeView);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w5.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.packageNameEntry.Changed += new global::System.EventHandler (this.OnPackageNameEntryChanged);
			this.treeView.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.HandleKeyPress);
		}
	}
}
