
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class DefineCompositeComponentWizard
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HPaned hpaned1;
		private global::TraceLab.UI.GTK.ExperimentCanvasWidget experimentcanvaswidget1;
		private global::Gtk.VBox mainVBox;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label stepIOSpecLabel;
		private global::Gtk.Label stepConfigLabel;
		private global::Gtk.Label stepComponentInfoLabel;
		private global::Gtk.Label stepConfirmationLabel;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button backButton;
		private global::Gtk.Button forwardButton;
		private global::Gtk.Button defineButton;
		private global::Gtk.Button cancelButton;
		private global::Gtk.Button okButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.DefineCompositeComponentWizard
			this.Name = "TraceLab.UI.GTK.DefineCompositeComponentWizard";
			this.Title = global::Mono.Unix.Catalog.GetString ("DefineCompositeComponentWizard");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child TraceLab.UI.GTK.DefineCompositeComponentWizard.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 300;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.experimentcanvaswidget1 = new global::TraceLab.UI.GTK.ExperimentCanvasWidget ();
			this.experimentcanvaswidget1.Events = ((global::Gdk.EventMask)(256));
			this.experimentcanvaswidget1.Name = "experimentcanvaswidget1";
			this.hpaned1.Add (this.experimentcanvaswidget1);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.experimentcanvaswidget1]));
			w1.Resize = false;
			w1.Shrink = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.mainVBox = new global::Gtk.VBox ();
			this.mainVBox.Name = "mainVBox";
			this.mainVBox.Spacing = 6;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(2));
			// Container child hbox1.Gtk.Box+BoxChild
			this.stepIOSpecLabel = new global::Gtk.Label ();
			this.stepIOSpecLabel.Name = "stepIOSpecLabel";
			this.stepIOSpecLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("1. IOSpec");
			this.hbox1.Add (this.stepIOSpecLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.stepIOSpecLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.stepConfigLabel = new global::Gtk.Label ();
			this.stepConfigLabel.Name = "stepConfigLabel";
			this.stepConfigLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("2. Configuration");
			this.hbox1.Add (this.stepConfigLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.stepConfigLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.stepComponentInfoLabel = new global::Gtk.Label ();
			this.stepComponentInfoLabel.Name = "stepComponentInfoLabel";
			this.stepComponentInfoLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("3. Component Info");
			this.hbox1.Add (this.stepComponentInfoLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.stepComponentInfoLabel]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.stepConfirmationLabel = new global::Gtk.Label ();
			this.stepConfirmationLabel.Name = "stepConfirmationLabel";
			this.stepConfirmationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("4. Confirmation");
			this.hbox1.Add (this.stepConfirmationLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.stepConfirmationLabel]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.mainVBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.hpaned1.Add (this.mainVBox);
			this.vbox2.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned1]));
			w8.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 10;
			this.hbuttonbox2.BorderWidth = ((uint)(3));
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.backButton = new global::Gtk.Button ();
			this.backButton.Sensitive = false;
			this.backButton.CanFocus = true;
			this.backButton.Name = "backButton";
			this.backButton.UseStock = true;
			this.backButton.UseUnderline = true;
			this.backButton.Label = "gtk-go-back";
			this.hbuttonbox2.Add (this.backButton);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.backButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.forwardButton = new global::Gtk.Button ();
			this.forwardButton.CanFocus = true;
			this.forwardButton.Name = "forwardButton";
			this.forwardButton.UseStock = true;
			this.forwardButton.UseUnderline = true;
			this.forwardButton.Label = "gtk-go-forward";
			this.hbuttonbox2.Add (this.forwardButton);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.forwardButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.defineButton = new global::Gtk.Button ();
			this.defineButton.CanFocus = true;
			this.defineButton.Name = "defineButton";
			// Container child defineButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("Define");
			w12.Add (w15);
			w11.Add (w12);
			this.defineButton.Add (w11);
			this.hbuttonbox2.Add (this.defineButton);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.defineButton]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseStock = true;
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = "gtk-cancel";
			this.hbuttonbox2.Add (this.cancelButton);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.cancelButton]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseStock = true;
			this.okButton.UseUnderline = true;
			this.okButton.Label = "gtk-ok";
			this.hbuttonbox2.Add (this.okButton);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.okButton]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 848;
			this.DefaultHeight = 478;
			this.defineButton.Hide ();
			this.okButton.Hide ();
			this.Show ();
			this.backButton.Clicked += new global::System.EventHandler (this.backButtonClicked);
			this.forwardButton.Clicked += new global::System.EventHandler (this.forwardButtonClicked);
			this.defineButton.Clicked += new global::System.EventHandler (this.defineButtonClicked);
			this.cancelButton.Clicked += new global::System.EventHandler (this.closeWindow);
			this.okButton.Clicked += new global::System.EventHandler (this.closeWindow);
		}
	}
}
