
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class ConfigSetupPage
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.VBox vbox2;
		private global::Gtk.TextView textview1;
		private global::Gtk.TreeView configView;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.ConfigSetupPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TraceLab.UI.GTK.ConfigSetupPage";
			// Container child TraceLab.UI.GTK.ConfigSetupPage.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(3));
			// Container child vbox2.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = @"Component is defined also by the configuration parameters.
All configuration parameters can be set by the component's user, but only some are visible in the top level view of component in its info pane. 
Please select config parameters that are going to be visible at the top level.";
			this.textview1.Sensitive = false;
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(1));
			this.textview1.LeftMargin = 4;
			this.textview1.RightMargin = 4;
			this.vbox2.Add (this.textview1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.textview1]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.configView = new global::Gtk.TreeView ();
			this.configView.CanFocus = true;
			this.configView.Name = "configView";
			this.vbox2.Add (this.configView);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.configView]));
			w3.Position = 1;
			w1.Add (this.vbox2);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
