
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class IOSpecSetupPage
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.VBox vbox3;
		private global::Gtk.TextView textview1;
		private global::Gtk.TreeView inputsView;
		private global::Gtk.TreeView outputsView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.IOSpecSetupPage
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TraceLab.UI.GTK.IOSpecSetupPage";
			// Container child TraceLab.UI.GTK.IOSpecSetupPage.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.Buffer.Text = "Component is defined by its inputs and outputs. \nPlease select inputs that your c" +
				"omponent will require to do its computation, and final outputs.";
			this.textview1.Sensitive = false;
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.CursorVisible = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.textview1.LeftMargin = 4;
			this.textview1.RightMargin = 4;
			this.vbox3.Add (this.textview1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.textview1]));
			w2.Position = 0;
			w2.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.inputsView = new global::Gtk.TreeView ();
			this.inputsView.CanFocus = true;
			this.inputsView.Name = "inputsView";
			this.vbox3.Add (this.inputsView);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.inputsView]));
			w3.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.outputsView = new global::Gtk.TreeView ();
			this.outputsView.CanFocus = true;
			this.outputsView.Name = "outputsView";
			this.vbox3.Add (this.outputsView);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.outputsView]));
			w4.Position = 2;
			w1.Add (this.vbox3);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
