
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class LoopDecisionInfoPanel
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button checkCodeButton1;
		private global::Gtk.Label componentLabelLbl;
		private global::Gtk.Entry componentLabelValue;
		private global::Gtk.Label decisionCodeLbl1;
		private global::Gtk.TextView errorTextView1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView decisionCodeEntryBox1;
		private global::Gtk.Table table2;
		private global::Gtk.ComboBox loadComboBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.LoopDecisionInfoPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TraceLab.UI.GTK.LoopDecisionInfoPanel";
			// Container child TraceLab.UI.GTK.LoopDecisionInfoPanel.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkCodeButton1 = new global::Gtk.Button ();
			this.checkCodeButton1.CanFocus = true;
			this.checkCodeButton1.Name = "checkCodeButton1";
			this.checkCodeButton1.UseUnderline = true;
			this.checkCodeButton1.Label = "Check correctness";
			this.table1.Add (this.checkCodeButton1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkCodeButton1]));
			w1.TopAttach = ((uint)(4));
			w1.BottomAttach = ((uint)(5));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.componentLabelLbl = new global::Gtk.Label ();
			this.componentLabelLbl.Name = "componentLabelLbl";
			this.componentLabelLbl.Xpad = 3;
			this.componentLabelLbl.Ypad = 2;
			this.componentLabelLbl.Xalign = 0F;
			this.componentLabelLbl.Yalign = 0F;
			this.componentLabelLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Label:");
			this.table1.Add (this.componentLabelLbl);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.componentLabelLbl]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.componentLabelValue = new global::Gtk.Entry ();
			this.componentLabelValue.CanFocus = true;
			this.componentLabelValue.Name = "componentLabelValue";
			this.componentLabelValue.IsEditable = true;
			this.componentLabelValue.InvisibleChar = '●';
			this.table1.Add (this.componentLabelValue);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.componentLabelValue]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.decisionCodeLbl1 = new global::Gtk.Label ();
			this.decisionCodeLbl1.Name = "decisionCodeLbl1";
			this.decisionCodeLbl1.Xpad = 3;
			this.decisionCodeLbl1.Xalign = 0F;
			this.decisionCodeLbl1.Yalign = 0F;
			this.decisionCodeLbl1.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter your \"loop while\" condition here: ");
			this.table1.Add (this.decisionCodeLbl1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.decisionCodeLbl1]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.errorTextView1 = new global::Gtk.TextView ();
			this.errorTextView1.CanFocus = true;
			this.errorTextView1.Name = "errorTextView1";
			this.errorTextView1.Editable = false;
			this.errorTextView1.CursorVisible = false;
			this.errorTextView1.AcceptsTab = false;
			this.errorTextView1.WrapMode = ((global::Gtk.WrapMode)(3));
			this.errorTextView1.LeftMargin = 3;
			this.errorTextView1.RightMargin = 3;
			this.table1.Add (this.errorTextView1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.errorTextView1]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.decisionCodeEntryBox1 = new global::Gtk.TextView ();
			this.decisionCodeEntryBox1.Buffer.Text = "For example:\n((int)Load(\"j\")>0);";
			this.decisionCodeEntryBox1.CanFocus = true;
			this.decisionCodeEntryBox1.Name = "decisionCodeEntryBox1";
			this.GtkScrolledWindow1.Add (this.decisionCodeEntryBox1);
			this.table1.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow1]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.loadComboBox = global::Gtk.ComboBox.NewText ();
			this.loadComboBox.Name = "loadComboBox";
			this.table2.Add (this.loadComboBox);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.loadComboBox]));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table1.Add (this.table2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.table2]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.errorTextView1.Hide ();
			this.Hide ();
			this.loadComboBox.Changed += new global::System.EventHandler (this.OnLoadComboBoxChanged);
			this.componentLabelValue.Changed += new global::System.EventHandler (this.labelChanged);
			this.checkCodeButton1.Clicked += new global::System.EventHandler (this.CheckCode);
		}
	}
}
