
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class SettingsDialog
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry tbx_defaultExperimentPath;
		private global::Gtk.Button button114;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment9;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.Label lbl_temporaryComponentDirectories;
		private global::Gtk.HBox hbox6;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView trv_componentDirectories;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Button button118;
		private global::Gtk.Button button120;
		private global::Gtk.Button button121;
		private global::Gtk.Button button122;
		private global::Gtk.Label GtkLabel13;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment11;
		private global::Gtk.VBox vbox8;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.Label lbl_temporaryTypesDirectories;
		private global::Gtk.HBox hbox3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView trv_typeDirectories;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Button button192;
		private global::Gtk.Button button193;
		private global::Gtk.Button button194;
		private global::Gtk.Button button195;
		private global::Gtk.Label GtkLabel16;
		private global::Gtk.Frame frame4;
		private global::Gtk.Alignment GtkAlignment17;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Entry tbx_defaultExperimentDirectory;
		private global::Gtk.Button button197;
		private global::Gtk.Label GtkLabel18;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.SettingsDialog
			this.Name = "TraceLab.UI.GTK.SettingsDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("TraceLab Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TraceLab.UI.GTK.SettingsDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tbx_defaultExperimentPath = new global::Gtk.Entry ();
			this.tbx_defaultExperimentPath.CanFocus = true;
			this.tbx_defaultExperimentPath.Name = "tbx_defaultExperimentPath";
			this.tbx_defaultExperimentPath.IsEditable = true;
			this.tbx_defaultExperimentPath.InvisibleChar = '•';
			this.hbox1.Add (this.tbx_defaultExperimentPath);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tbx_defaultExperimentPath]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button114 = new global::Gtk.Button ();
			this.button114.CanFocus = true;
			this.button114.Name = "button114";
			this.button114.UseUnderline = true;
			// Container child button114.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Select");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.button114.Add (w3);
			this.hbox1.Add (this.button114);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button114]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.GtkAlignment2.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Default Experiment</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment9 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment9.HeightRequest = 0;
			this.GtkAlignment9.Name = "GtkAlignment9";
			this.GtkAlignment9.LeftPadding = ((uint)(12));
			// Container child GtkAlignment9.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w15 = new global::Gtk.Viewport ();
			w15.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.lbl_temporaryComponentDirectories = new global::Gtk.Label ();
			this.lbl_temporaryComponentDirectories.Name = "lbl_temporaryComponentDirectories";
			this.lbl_temporaryComponentDirectories.UseMarkup = true;
			this.lbl_temporaryComponentDirectories.Selectable = true;
			w15.Add (this.lbl_temporaryComponentDirectories);
			this.GtkScrolledWindow2.Add (w15);
			this.vbox4.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow2]));
			w18.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trv_componentDirectories = new global::Gtk.TreeView ();
			this.trv_componentDirectories.CanFocus = true;
			this.trv_componentDirectories.Name = "trv_componentDirectories";
			this.GtkScrolledWindow.Add (this.trv_componentDirectories);
			this.hbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.GtkScrolledWindow]));
			w20.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button118 = new global::Gtk.Button ();
			this.button118.CanFocus = true;
			this.button118.Name = "button118";
			this.button118.UseUnderline = true;
			// Container child button118.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Up");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.button118.Add (w21);
			this.vbox7.Add (this.button118);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.button118]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button120 = new global::Gtk.Button ();
			this.button120.CanFocus = true;
			this.button120.Name = "button120";
			this.button120.UseUnderline = true;
			// Container child button120.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w34.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Down");
			w34.UseUnderline = true;
			w31.Add (w34);
			w30.Add (w31);
			this.button120.Add (w30);
			this.vbox7.Add (this.button120);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.button120]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button121 = new global::Gtk.Button ();
			this.button121.CanFocus = true;
			this.button121.Name = "button121";
			this.button121.UseUnderline = true;
			// Container child button121.Gtk.Container+ContainerChild
			global::Gtk.Alignment w39 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w40 = new global::Gtk.HBox ();
			w40.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w40.Add (w41);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w43.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w43.UseUnderline = true;
			w40.Add (w43);
			w39.Add (w40);
			this.button121.Add (w39);
			this.vbox7.Add (this.button121);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.button121]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button122 = new global::Gtk.Button ();
			this.button122.CanFocus = true;
			this.button122.Name = "button122";
			this.button122.UseUnderline = true;
			// Container child button122.Gtk.Container+ContainerChild
			global::Gtk.Alignment w48 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w49 = new global::Gtk.HBox ();
			w49.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w50 = new global::Gtk.Image ();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w49.Add (w50);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w52 = new global::Gtk.Label ();
			w52.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
			w52.UseUnderline = true;
			w49.Add (w52);
			w48.Add (w49);
			this.button122.Add (w48);
			this.vbox7.Add (this.button122);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.button122]));
			w56.Position = 3;
			w56.Expand = false;
			w56.Fill = false;
			this.hbox6.Add (this.vbox7);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox7]));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.vbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w59.Position = 0;
			this.GtkAlignment9.Add (this.hbox2);
			this.frame2.Add (this.GtkAlignment9);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Component Directories</b>");
			this.GtkLabel13.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel13;
			this.vbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame2]));
			w62.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment11 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment11.Name = "GtkAlignment11";
			this.GtkAlignment11.LeftPadding = ((uint)(12));
			// Container child GtkAlignment11.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w63 = new global::Gtk.Viewport ();
			w63.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.lbl_temporaryTypesDirectories = new global::Gtk.Label ();
			this.lbl_temporaryTypesDirectories.Name = "lbl_temporaryTypesDirectories";
			this.lbl_temporaryTypesDirectories.UseMarkup = true;
			this.lbl_temporaryTypesDirectories.Selectable = true;
			w63.Add (this.lbl_temporaryTypesDirectories);
			this.GtkScrolledWindow3.Add (w63);
			this.vbox8.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow3]));
			w66.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.trv_typeDirectories = new global::Gtk.TreeView ();
			this.trv_typeDirectories.CanFocus = true;
			this.trv_typeDirectories.Name = "trv_typeDirectories";
			this.GtkScrolledWindow1.Add (this.trv_typeDirectories);
			this.hbox3.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow1]));
			w68.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.button192 = new global::Gtk.Button ();
			this.button192.CanFocus = true;
			this.button192.Name = "button192";
			this.button192.UseUnderline = true;
			// Container child button192.Gtk.Container+ContainerChild
			global::Gtk.Alignment w69 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w70 = new global::Gtk.HBox ();
			w70.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w71 = new global::Gtk.Image ();
			w71.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w70.Add (w71);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w73 = new global::Gtk.Label ();
			w73.LabelProp = global::Mono.Unix.Catalog.GetString ("Move up");
			w73.UseUnderline = true;
			w70.Add (w73);
			w69.Add (w70);
			this.button192.Add (w69);
			this.vbox5.Add (this.button192);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button192]));
			w77.Position = 0;
			w77.Expand = false;
			w77.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.button193 = new global::Gtk.Button ();
			this.button193.CanFocus = true;
			this.button193.Name = "button193";
			this.button193.UseUnderline = true;
			// Container child button193.Gtk.Container+ContainerChild
			global::Gtk.Alignment w78 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w79 = new global::Gtk.HBox ();
			w79.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w80 = new global::Gtk.Image ();
			w80.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			w79.Add (w80);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w82 = new global::Gtk.Label ();
			w82.LabelProp = global::Mono.Unix.Catalog.GetString ("Move Down");
			w82.UseUnderline = true;
			w79.Add (w82);
			w78.Add (w79);
			this.button193.Add (w78);
			this.vbox5.Add (this.button193);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button193]));
			w86.Position = 1;
			w86.Expand = false;
			w86.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.button194 = new global::Gtk.Button ();
			this.button194.CanFocus = true;
			this.button194.Name = "button194";
			this.button194.UseUnderline = true;
			// Container child button194.Gtk.Container+ContainerChild
			global::Gtk.Alignment w87 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w88 = new global::Gtk.HBox ();
			w88.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w89 = new global::Gtk.Image ();
			w89.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w88.Add (w89);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w91 = new global::Gtk.Label ();
			w91.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w91.UseUnderline = true;
			w88.Add (w91);
			w87.Add (w88);
			this.button194.Add (w87);
			this.vbox5.Add (this.button194);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button194]));
			w95.Position = 2;
			w95.Expand = false;
			w95.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.button195 = new global::Gtk.Button ();
			this.button195.CanFocus = true;
			this.button195.Name = "button195";
			this.button195.UseUnderline = true;
			// Container child button195.Gtk.Container+ContainerChild
			global::Gtk.Alignment w96 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w97 = new global::Gtk.HBox ();
			w97.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w98 = new global::Gtk.Image ();
			w98.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w97.Add (w98);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w100 = new global::Gtk.Label ();
			w100.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
			w100.UseUnderline = true;
			w97.Add (w100);
			w96.Add (w97);
			this.button195.Add (w96);
			this.vbox5.Add (this.button195);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.button195]));
			w104.Position = 3;
			w104.Expand = false;
			w104.Fill = false;
			this.hbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox5]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			this.vbox8.Add (this.hbox3);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox3]));
			w106.Position = 1;
			w106.Expand = false;
			w106.Fill = false;
			this.GtkAlignment11.Add (this.vbox8);
			this.frame3.Add (this.GtkAlignment11);
			this.GtkLabel16 = new global::Gtk.Label ();
			this.GtkLabel16.Name = "GtkLabel16";
			this.GtkLabel16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Type Directories</b>");
			this.GtkLabel16.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel16;
			this.vbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
			w109.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame ();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment17 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment17.Name = "GtkAlignment17";
			this.GtkAlignment17.LeftPadding = ((uint)(12));
			// Container child GtkAlignment17.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.tbx_defaultExperimentDirectory = new global::Gtk.Entry ();
			this.tbx_defaultExperimentDirectory.CanFocus = true;
			this.tbx_defaultExperimentDirectory.Name = "tbx_defaultExperimentDirectory";
			this.tbx_defaultExperimentDirectory.IsEditable = true;
			this.tbx_defaultExperimentDirectory.InvisibleChar = '•';
			this.hbox4.Add (this.tbx_defaultExperimentDirectory);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.tbx_defaultExperimentDirectory]));
			w110.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button197 = new global::Gtk.Button ();
			this.button197.CanFocus = true;
			this.button197.Name = "button197";
			this.button197.UseUnderline = true;
			// Container child button197.Gtk.Container+ContainerChild
			global::Gtk.Alignment w111 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w112 = new global::Gtk.HBox ();
			w112.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w113 = new global::Gtk.Image ();
			w113.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			w112.Add (w113);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w115 = new global::Gtk.Label ();
			w115.LabelProp = global::Mono.Unix.Catalog.GetString ("Select");
			w115.UseUnderline = true;
			w112.Add (w115);
			w111.Add (w112);
			this.button197.Add (w111);
			this.hbox4.Add (this.button197);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button197]));
			w119.Position = 1;
			w119.Expand = false;
			w119.Fill = false;
			this.GtkAlignment17.Add (this.hbox4);
			this.frame4.Add (this.GtkAlignment17);
			this.GtkLabel18 = new global::Gtk.Label ();
			this.GtkLabel18.Name = "GtkLabel18";
			this.GtkLabel18.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Experiments Directory</b>");
			this.GtkLabel18.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel18;
			this.vbox3.Add (this.frame4);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
			w122.Position = 3;
			w122.Expand = false;
			w122.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w123.Position = 0;
			// Internal child TraceLab.UI.GTK.SettingsDialog.ActionArea
			global::Gtk.HButtonBox w124 = this.ActionArea;
			w124.Name = "dialog1_ActionArea";
			w124.Spacing = 10;
			w124.BorderWidth = ((uint)(5));
			w124.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w125 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w126 = new global::Gtk.HBox ();
			w126.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w127 = new global::Gtk.Image ();
			w127.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w126.Add (w127);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w129 = new global::Gtk.Label ();
			w129.LabelProp = global::Mono.Unix.Catalog.GetString ("_Cancel");
			w129.UseUnderline = true;
			w126.Add (w129);
			w125.Add (w126);
			this.buttonCancel.Add (w125);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w133 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w124 [this.buttonCancel]));
			w133.Expand = false;
			w133.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w134 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w135 = new global::Gtk.HBox ();
			w135.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w136 = new global::Gtk.Image ();
			w136.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w135.Add (w136);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w138 = new global::Gtk.Label ();
			w138.LabelProp = global::Mono.Unix.Catalog.GetString ("Save Changes");
			w138.UseUnderline = true;
			w135.Add (w138);
			w134.Add (w135);
			this.buttonOk.Add (w134);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w142 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w124 [this.buttonOk]));
			w142.Position = 1;
			w142.Expand = false;
			w142.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 709;
			this.DefaultHeight = 584;
			this.Show ();
			this.button114.Clicked += new global::System.EventHandler (this.defaultExperimentSelectClickedHandler);
			this.button118.Clicked += new global::System.EventHandler (this.componentDirectoryMoveUpClickedHandler);
			this.button120.Clicked += new global::System.EventHandler (this.componentDirectoryMoveDownClickedHandler);
			this.button121.Clicked += new global::System.EventHandler (this.addComponentDirectoryClickedHandler);
			this.button122.Clicked += new global::System.EventHandler (this.componentDirectoryDeleteClickedHandler);
			this.button192.Clicked += new global::System.EventHandler (this.typesDirectoryMoveUpClickedHandler);
			this.button193.Clicked += new global::System.EventHandler (this.typesDirectoryMoveDownClickedHandler);
			this.button194.Clicked += new global::System.EventHandler (this.addTypesDirectoryClickedHandler);
			this.button195.Clicked += new global::System.EventHandler (this.typesDirectoryDeleteClickedHandler);
			this.button197.Clicked += new global::System.EventHandler (this.defaultExperimentDirectorySelectFolderClickedHandler);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.cancelClickedHandler);
			this.buttonOk.Clicked += new global::System.EventHandler (this.saveChangesClickedHandler);
		}
	}
}
