
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class DecisionInfoPanel
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button checkCodeButton;
		private global::Gtk.Label componentLabelLbl;
		private global::Gtk.Entry componentLabelValue;
		private global::Gtk.Label decisionCodeLbl;
		private global::Gtk.TextView errorTextView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView decisionCodeEntryBox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.DecisionInfoPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TraceLab.UI.GTK.DecisionInfoPanel";
			// Container child TraceLab.UI.GTK.DecisionInfoPanel.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkCodeButton = new global::Gtk.Button ();
			this.checkCodeButton.CanFocus = true;
			this.checkCodeButton.Name = "checkCodeButton";
			this.checkCodeButton.UseUnderline = true;
			this.checkCodeButton.Label = "Check code";
			this.table1.Add (this.checkCodeButton);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkCodeButton]));
			w1.TopAttach = ((uint)(4));
			w1.BottomAttach = ((uint)(5));
			w1.RightAttach = ((uint)(2));
			w1.XPadding = ((uint)(2));
			w1.YPadding = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.componentLabelLbl = new global::Gtk.Label ();
			this.componentLabelLbl.Name = "componentLabelLbl";
			this.componentLabelLbl.Xpad = 3;
			this.componentLabelLbl.Ypad = 2;
			this.componentLabelLbl.Xalign = 0F;
			this.componentLabelLbl.Yalign = 0F;
			this.componentLabelLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Label:");
			this.table1.Add (this.componentLabelLbl);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.componentLabelLbl]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XPadding = ((uint)(2));
			w2.YPadding = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.componentLabelValue = new global::Gtk.Entry ();
			this.componentLabelValue.CanFocus = true;
			this.componentLabelValue.Name = "componentLabelValue";
			this.componentLabelValue.IsEditable = true;
			this.componentLabelValue.InvisibleChar = '●';
			this.table1.Add (this.componentLabelValue);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.componentLabelValue]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XPadding = ((uint)(2));
			w3.YPadding = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.decisionCodeLbl = new global::Gtk.Label ();
			this.decisionCodeLbl.Name = "decisionCodeLbl";
			this.decisionCodeLbl.Xpad = 3;
			this.decisionCodeLbl.Xalign = 0F;
			this.decisionCodeLbl.Yalign = 0F;
			this.decisionCodeLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("DecisionCode: ");
			this.table1.Add (this.decisionCodeLbl);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.decisionCodeLbl]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.RightAttach = ((uint)(2));
			w4.XPadding = ((uint)(2));
			w4.YPadding = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.errorTextView = new global::Gtk.TextView ();
			this.errorTextView.CanFocus = true;
			this.errorTextView.Name = "errorTextView";
			this.errorTextView.Editable = false;
			this.errorTextView.CursorVisible = false;
			this.errorTextView.AcceptsTab = false;
			this.errorTextView.Justification = ((global::Gtk.Justification)(3));
			this.errorTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.errorTextView.LeftMargin = 3;
			this.errorTextView.RightMargin = 3;
			this.table1.Add (this.errorTextView);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.errorTextView]));
			w5.RightAttach = ((uint)(2));
			w5.XPadding = ((uint)(3));
			w5.YPadding = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(6));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.decisionCodeEntryBox = new global::Gtk.TextView ();
			this.decisionCodeEntryBox.Buffer.Text = "// here is sample condition code\r\n\r\nif(Load(\"provide variable from workspace\") < " +
				"0) {\r\n  Select(\"provide next component label\");\r\n} else {\r\n  Select(\"provide nex" +
				"t component label\");\r\n}\r\n";
			this.decisionCodeEntryBox.CanFocus = true;
			this.decisionCodeEntryBox.Name = "decisionCodeEntryBox";
			this.GtkScrolledWindow.Add (this.decisionCodeEntryBox);
			this.table1.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow]));
			w7.TopAttach = ((uint)(3));
			w7.BottomAttach = ((uint)(4));
			w7.RightAttach = ((uint)(2));
			w7.XPadding = ((uint)(2));
			w7.YPadding = ((uint)(2));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.errorTextView.Hide ();
			this.Hide ();
			this.componentLabelValue.Changed += new global::System.EventHandler (this.labelChanged);
			this.checkCodeButton.Clicked += new global::System.EventHandler (this.CheckCode);
		}
	}
}
