
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class PasswordPicker
	{
		private global::Gtk.Table table1;
		private global::Gtk.Label challengePassword;
		private global::Gtk.Entry challengePwdEntry;
		private global::Gtk.Label experimentPassword;
		private global::Gtk.Entry experimentPwdEntry;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.Entry reinsChallengePwdEntry;
		private global::Gtk.Label reinsertChallengePassword;
		private global::Gtk.Label reinsertExperimentPassword;
		private global::Gtk.Entry reinsExperimentPwdEntry;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.PasswordPicker
			this.Name = "TraceLab.UI.GTK.PasswordPicker";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child TraceLab.UI.GTK.PasswordPicker.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.challengePassword = new global::Gtk.Label ();
			this.challengePassword.Name = "challengePassword";
			this.challengePassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Challenge Password");
			this.table1.Add (this.challengePassword);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.challengePassword]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.challengePwdEntry = new global::Gtk.Entry ();
			this.challengePwdEntry.CanFocus = true;
			this.challengePwdEntry.Name = "challengePwdEntry";
			this.challengePwdEntry.IsEditable = true;
			this.challengePwdEntry.InvisibleChar = '●';
			this.table1.Add (this.challengePwdEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.challengePwdEntry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.experimentPassword = new global::Gtk.Label ();
			this.experimentPassword.Name = "experimentPassword";
			this.experimentPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Experiment Password");
			this.table1.Add (this.experimentPassword);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.experimentPassword]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.experimentPwdEntry = new global::Gtk.Entry ();
			this.experimentPwdEntry.CanFocus = true;
			this.experimentPwdEntry.Name = "experimentPwdEntry";
			this.experimentPwdEntry.IsEditable = true;
			this.experimentPwdEntry.InvisibleChar = '●';
			this.table1.Add (this.experimentPwdEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.experimentPwdEntry]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.table1.Add (this.hseparator1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator1]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.table1.Add (this.hseparator2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hseparator2]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reinsChallengePwdEntry = new global::Gtk.Entry ();
			this.reinsChallengePwdEntry.CanFocus = true;
			this.reinsChallengePwdEntry.Name = "reinsChallengePwdEntry";
			this.reinsChallengePwdEntry.IsEditable = true;
			this.reinsChallengePwdEntry.InvisibleChar = '●';
			this.table1.Add (this.reinsChallengePwdEntry);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.reinsChallengePwdEntry]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reinsertChallengePassword = new global::Gtk.Label ();
			this.reinsertChallengePassword.Name = "reinsertChallengePassword";
			this.reinsertChallengePassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Repeat Password");
			this.table1.Add (this.reinsertChallengePassword);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.reinsertChallengePassword]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reinsertExperimentPassword = new global::Gtk.Label ();
			this.reinsertExperimentPassword.Name = "reinsertExperimentPassword";
			this.reinsertExperimentPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Repeat Password");
			this.table1.Add (this.reinsertExperimentPassword);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.reinsertExperimentPassword]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.reinsExperimentPwdEntry = new global::Gtk.Entry ();
			this.reinsExperimentPwdEntry.CanFocus = true;
			this.reinsExperimentPwdEntry.Name = "reinsExperimentPwdEntry";
			this.reinsExperimentPwdEntry.IsEditable = true;
			this.reinsExperimentPwdEntry.InvisibleChar = '●';
			this.table1.Add (this.reinsExperimentPwdEntry);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.reinsExperimentPwdEntry]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Internal child TraceLab.UI.GTK.PasswordPicker.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 10;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonCancel]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonOk]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 436;
			this.DefaultHeight = 218;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
