
// This file has been generated by the GUI designer. Do not modify.
namespace TraceLab.UI.GTK
{
	public partial class PackageBuilderWindow
	{
		private global::Gtk.VBox frameVBox;
		private global::Gtk.VBox mainVBox;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button generateButton;
		private global::Gtk.Button buildPackageButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TraceLab.UI.GTK.PackageBuilderWindow
			this.Name = "TraceLab.UI.GTK.PackageBuilderWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PackageBuilderWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child TraceLab.UI.GTK.PackageBuilderWindow.Gtk.Container+ContainerChild
			this.frameVBox = new global::Gtk.VBox ();
			this.frameVBox.Name = "frameVBox";
			this.frameVBox.Spacing = 6;
			// Container child frameVBox.Gtk.Box+BoxChild
			this.mainVBox = new global::Gtk.VBox ();
			this.mainVBox.Name = "mainVBox";
			this.mainVBox.Spacing = 6;
			this.frameVBox.Add (this.mainVBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.frameVBox [this.mainVBox]));
			w1.Position = 0;
			// Container child frameVBox.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Spacing = 5;
			this.hbuttonbox1.BorderWidth = ((uint)(5));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.generateButton = new global::Gtk.Button ();
			this.generateButton.CanFocus = true;
			this.generateButton.Name = "generateButton";
			this.generateButton.UseUnderline = true;
			this.generateButton.Label = global::Mono.Unix.Catalog.GetString ("Generate");
			this.hbuttonbox1.Add (this.generateButton);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.generateButton]));
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.buildPackageButton = new global::Gtk.Button ();
			this.buildPackageButton.CanFocus = true;
			this.buildPackageButton.Name = "buildPackageButton";
			this.buildPackageButton.UseUnderline = true;
			this.buildPackageButton.Label = global::Mono.Unix.Catalog.GetString ("Build Package");
			this.hbuttonbox1.Add (this.buildPackageButton);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.buildPackageButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.frameVBox.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.frameVBox [this.hbuttonbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.frameVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 555;
			this.DefaultHeight = 265;
			this.generateButton.Hide ();
			this.buildPackageButton.Hide ();
			this.Show ();
			this.generateButton.Clicked += new global::System.EventHandler (this.generateButtonClicked);
			this.buildPackageButton.Clicked += new global::System.EventHandler (this.buildButtonClicked);
		}
	}
}
