
// This file has been generated by the GUI designer. Do not modify.
namespace MonoHotDraw
{
	public partial class SteticComponent
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoHotDraw.SteticComponent
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoHotDraw.SteticComponent";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
